### ISSUE TITLE
numpy.core array memory error: unable to allocate X.

### ISSUE THREAD

**Issue by PyMarc2** [DCC-Lab/PyTissueOptics#87]
When using on PC with window 10 x64.
This code
```    
materialLayer1 = ScatteringMaterial(mu_s=0, mu_a=1, g=0.7, n=1.38)
materialLayer2 = ScatteringMaterial(mu_s=90, mu_a=0.01, g=0.8, n=1.33)
materialLayer3 = ScatteringMaterial(mu_s=1, mu_a=1, g=1, n=1.2)
materialLayer4 = ScatteringMaterial(mu_s=100, mu_a=50, g=1, n=1)

layer1 = Cuboid(a=300, b=300, c=5, position=Vector(0, 0, 0), material=materialLayer1, label="Layer 1")
layer2 = Cuboid(a=300, b=300, c=10, position=Vector(0, 0, 0), material=materialLayer2, label="Layer 2")
layer3 = Cuboid(a=300, b=300, c=5, position=Vector(0, 0, 0), material=materialLayer3, label="Layer 3")
layer4 = Cuboid(a=300, b=300, c=260, position=Vector(0, 0, 0), material=materialLayer4, label="Layer 4")

stack1 = layer1.stack(layer2, "back")
stack2 = stack1.stack(layer3, "back")
stackedTissue = stack2.stack(layer4, "back")

tissue = ScatteringScene([stackedTissue])

logger = EnergyLogger(tissue)
source = PencilPointSource(position=Vector(0, 0, -5), direction=Vector(0, 0, 1), N=500)
source.propagate(tissue, logger)
viewer = Viewer(tissue, source, logger)
viewer.reportStats()
viewer.show3DVolumeSlicer()
```
Produces this error. Even if this is probably because python is not given enough memory, error should be caught and the source explained so the user can correct.
```
Traceback (most recent call last):
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\examples\rayscattering\ex05.py", line 39, in <module>
    exampleCode()
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\examples\rayscattering\ex05.py", line 29, in exampleCode
    logger = EnergyLogger(tissue)
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\pytissueoptics\rayscattering\energyLogging\energyLogger.py", line 48, in __init__
    self._views = self._viewFactory.build(views)
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\pytissueoptics\rayscattering\display\views\viewFactory.py", line 29, in build
    self._setContext(view)
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\pytissueoptics\rayscattering\display\views\viewFactory.py", line 104, in _setContext
    view.setContext(limits3D=limits3D, binSize3D=self._defaultBinSize3D)
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\pytissueoptics\rayscattering\display\views\view2D.py", line 96, in setContext
    self._dataUV = np.zeros((self._binsU, self._binsV), dtype=np.float32)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 3.35 GiB for an array with shape (30000, 30000) and data type float32
```

**Comment by PyMarc2** [comment]
Reducing layer size launches the simulation, but uncaught memory problems still arise
```
 layer1 = Cuboid(a=30, b=30, c=5, position=Vector(0, 0, 0), material=materialLayer1, label="Layer 1")
    layer2 = Cuboid(a=30, b=30, c=10, position=Vector(0, 0, 0), material=materialLayer2, label="Layer 2")
    layer3 = Cuboid(a=30, b=30, c=5, position=Vector(0, 0, 0), material=materialLayer3, label="Layer 3")
    layer4 = Cuboid(a=30, b=30, c=260, position=Vector(0, 0, 0), material=materialLayer4, label="Layer 4")
```
This modification gives
```
Propagating photons: 100%|██████████| 500/500 [00:02<00:00, 189.30it/s]
WARNING: The volume slicer will require a lot of memory (5632.64 GB). Consider using a larger binSize or tighter limits.
Traceback (most recent call last):
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\examples\rayscattering\ex05.py", line 39, in <module>
    exampleCode()
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\examples\rayscattering\ex05.py", line 35, in exampleCode
    viewer.show3DVolumeSlicer()
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\pytissueoptics\rayscattering\display\viewer.py", line 147, in show3DVolumeSlicer
    hist, _ = np.histogramdd(points[:, 1:], bins=bins, weights=points[:, 0], range=limits)
  File "<__array_function__ internals>", line 200, in histogramdd
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\venv\lib\site-packages\numpy\lib\histograms.py", line 1046, in histogramdd
    hist = np.bincount(xy, weights, minlength=nbin.prod())
  File "<__array_function__ internals>", line 200, in bincount
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 1.84 TiB for an array with shape (252354136008,) and data type float64
Report of solid 'Layer 1'
  Absorbance: 99.38% (96.47% of total power)
  Absorbance + Transmittance: 100.0%
    Transmittance at 'Layer 1_front': 0.0%
    Transmittance at 'interface0': 0.6%
Report of solid 'Layer 2'
  Absorbance: 22.30% (0.13% of total power)
  Absorbance + Transmittance: 100.0%
    Transmittance at 'interface0': 77.7%

```

**Comment by JLBegin** [comment]
The first case uses a large tissue of 3x3x3 meters. The logger initializes multiple default 2D views as empty arrays with a default bin size of 100 microns. We could skip this empty initialization when `keep3D` is left to True, and/or change the default bin size to adjust for scene size. 

In the second case, the crash happens when creating the volume slicer (with default bin size of 100 microns -> requiring over 5TB of memory). A warning is first written : 
> WARNING: The volume slicer will require a lot of memory (5632.64 GB). Consider using a larger binSize or tighter limits.

But we should also catch the OOM error. 

In the meantime, both errors should be avoidable by providing a proper `defaultBinSize` to the EnergyLogger

**Comment by PyMarc2** [comment]
there's also a third case, when the memory error only occurs when `show3D` is launched. In this case no warning is issued. Maybe 
```
materialLayer1 = ScatteringMaterial(mu_s=2, mu_a=0.5, g=0.7, n=1.3)
materialLayer2 = ScatteringMaterial(mu_s=5, mu_a=0.8, g=0.8, n=1.4)
materialLayer3 = ScatteringMaterial(mu_s=50, mu_a=2.5, g=0.9, n=1.5)

layer1 = Cuboid(a=100, b=100, c=5, position=Vector(0, 0, 0), material=materialLayer1, label="Layer 1")
layer2 = Cuboid(a=100, b=100, c=5, position=Vector(0, 0, 0), material=materialLayer2, label="Layer 2")
layer3 = Cuboid(a=100, b=100, c=5, position=Vector(0, 0, 0), material=materialLayer3, label="Layer 3")
stack1 = layer1.stack(layer2, "back")
stackedTissue = stack1.stack(layer3, "back")

tissue = ScatteringScene([stackedTissue])

logger = EnergyLogger(tissue, keep3D=False)
source = PencilPointSource(position=Vector(0, 0, -5), direction=Vector(0, 0, 1), N=500000, useHardwareAcceleration=True)
source.propagate(tissue, logger)

viewer = Viewer(tissue, source, logger)
viewer.reportStats()
viewer.show3D()
```

```
Traceback (most recent call last):
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\examples\rayscattering\ex04.py", line 35, in <module>
    exampleCode()
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\examples\rayscattering\ex04.py", line 31, in exampleCode
    viewer.show3D()
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\pytissueoptics\rayscattering\display\viewer.py", line 120, in show3D
    self._addViews(viewsVisibility, viewsSolidLabels, viewsSurfaceLabels, viewsLogScale, viewsColormap)
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\pytissueoptics\rayscattering\display\viewer.py", line 223, in _addViews
    self._addView(view, logScale, colormap)
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\pytissueoptics\rayscattering\display\viewer.py", line 253, in _addView
    self._viewer3D.addImage(alignedImage, alignedSize, alignedCorner, view.axis, view.displayPosition, colormap)
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\pytissueoptics\scene\viewer\mayavi\MayaviViewer.py", line 104, in addImage
    p = mlab.imshow(image, colormap=colormap, interpolate=False,
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\venv\lib\site-packages\mayavi\tools\helper_functions.py", line 38, in the_function
    return pipeline(*args, **kwargs)
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\venv\lib\site-packages\mayavi\tools\helper_functions.py", line 83, in __call__
    output = self.__call_internal__(*args, **kwargs)
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\venv\lib\site-packages\mayavi\tools\helper_functions.py", line 93, in __call_internal__
    self.source = self._source_function(*args, **kwargs)
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\venv\lib\site-packages\mayavi\tools\sources.py", line 1253, in array2d_source
    data_source.reset(scalars=s, mask=mask)
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\venv\lib\site-packages\mayavi\tools\sources.py", line 577, in reset
    x, y = np.mgrid[-nx / 2.:nx / 2, -ny / 2.:ny / 2]
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\venv\lib\site-packages\numpy\lib\index_tricks.py", line 174, in __getitem__
    nn = _nx.indices(size, typ)
  File "C:\Users\CAMAVIG2\Documents\GitHub\Python\PyTissueOptics\venv\lib\site-packages\numpy\core\numeric.py", line 1782, in indices
    res = empty((N,)+dimensions, dtype=dtype)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 37.3 GiB for an array with shape (2, 50000, 50000) and data type float64
```
