### ISSUE TITLE
Basic example crashes

### ISSUE THREAD

**Issue by dcxSt** [DCC-Lab/PyTissueOptics#92]
**Not able to run basic example**
I'm not able to run the example from the readme after pip installing the latest release. 

```
Traceback (most recent call last):
  File "/Users/steve/Documents/code/neuroimagery2023/PyTissueOptics/test.py", line 1, in <module>
    from pytissueoptics import *
  File "/Users/steve/Documents/code/neuroimagery2023/PyTissueOptics/pytissueoptics/__init__.py", line 2, in <module>
    from .rayscattering import *
  File "/Users/steve/Documents/code/neuroimagery2023/PyTissueOptics/pytissueoptics/rayscattering/__init__.py", line 4, in <module>
    from .source import PencilPointSource, IsotropicPointSource, DirectionalSource, DivergentSource
  File "/Users/steve/Documents/code/neuroimagery2023/PyTissueOptics/pytissueoptics/rayscattering/source.py", line 8, in <module>
    from pytissueoptics.rayscattering.opencl.CLPhotons import CLPhotons
  File "/Users/steve/Documents/code/neuroimagery2023/PyTissueOptics/pytissueoptics/rayscattering/opencl/__init__.py", line 1, in <module>
    from pytissueoptics.rayscattering.opencl.config.CLConfig import warnings, CLConfig, OPENCL_AVAILABLE, WEIGHT_THRESHOLD
  File "/Users/steve/Documents/code/neuroimagery2023/PyTissueOptics/pytissueoptics/rayscattering/opencl/config/CLConfig.py", line 36, in <module>
    class CLConfig:
  File "/Users/steve/Documents/code/neuroimagery2023/PyTissueOptics/pytissueoptics/rayscattering/opencl/config/CLConfig.py", line 188, in CLConfig
    def _devices(self) -> List[cl.Device]:
NameError: name 'cl' is not defined
```

**To Reproduce**
`pip install pytissueoptics`
Run
```python
from pytissueoptics import *

material = ScatteringMaterial(mu_s=3.0, mu_a=1.0, g=0.8, n=1.5)

tissue = Cuboid(a=1, b=3, c=1, position=Vector(2, 0, 0), material=material)
scene = ScatteringScene([tissue])

logger = EnergyLogger(scene)
source = PencilPointSource(position=Vector(-3, 0, 0), direction=Vector(1, 0, 0), N=1000)
source.propagate(scene, logger)

viewer = Viewer(scene, source, logger)
viewer.reportStats()
viewer.show3D()
```

**Expected behavior**
Not an error.

**Screenshots**
<img width="714" alt="Screenshot 2023-09-10 at 6 03 00 PM" src="https://github.com/DCC-Lab/PyTissueOptics/assets/21654151/1a6d5d3f-5fa1-4dce-8eff-7aa0a5cc7ede">

**Desktop:**
 - OS: macOS, Ventura 13.4
 - Python Version 3.9.13

**Additional context**
- I'm running on the M1 silicon, ARM architecture. 
- Also tried building from source, didn't work. 
- Unable to install `pyqt5` backend on ARM architectur.

**Comment by JLBegin** [comment]
The error occurs because `pyopencl` is not installed. 

From the traceback, I see that you have cloned the development version. This is great, but it requires you to install a few packages (including `pyopencl`).

This is done from the main `PyTissueOptics` folder by running the following command:
```bash
pip install -r requirements.txt
```
Depending on the version installed, you might have to also run the following command (if the file exists):
```bash
pip install -r requirements-optional.txt
```

Thanks for your feedback, I will improve the error handling to print proper instructions. 

I also just noticed that you had trouble installing PyQt5, which might have interrupted installation of the other packages. You could install them one by one if thats the case, but I doubt the program will run without a version of PyQt installed. If PyQt5 is not supported by Apple silicon chips, this might deserve its own issue that I will need to investigate. Depending on backcompatibility, you could attempt to install PyQt6 instead.
